### PR TITLE
Add what you see is what you get for messages and aboutMe

### PR DESCRIPTION
**Pull request by pabloemilio97**
* Modify data sanitization for input: accept basic html and images
* Ad ckEditor for messages and about me

### CODE REVIEW

**Comment by osjuga** [comment]
Looks good (unless you want to deal with whitespace before merging?)!

**Review by osjuga — APPROVED** [review]

**Review by gauravmishra — CHANGES_REQUESTED** [review]
(As we discussed on chat) remove whitespaces using a formatter

**Comment by pabloemilio97** [comment]
> (As we discussed on chat) remove whitespaces using a formatter

@gauravmishra Can we speak about this tomorrow in person?

**Comment by pabloemilio97** [comment]
@gauravmishra I'm going to fix java files format with the plugin we discussed, in another PR.

**Review by gauravmishra — APPROVED** [review]

**Pull request merged**
